name: Build and GH-Page Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./svelte

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: ./data-collection

      - name: Run data pipeline
        env:
          MAL_KEY: ${{ secrets.MAL_KEY }}
        run: |
          npm ci
          npm run layout
        working-directory: ./data-collection

      - name: Install
        run: npm ci
        working-directory: ./svelte

      - name: Build
        run: |
          npm run build
        working-directory: ./svelte

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: svelte/public
